version: 0.2

# Environment variables can be set in CodeBuild project
# or passed through parameter store/secrets manager
env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    IMAGE_REPO_NAME: "data-governance-tool"
    IMAGE_TAG: "latest"
  parameter-store:
    # Optionally pull secrets from AWS Systems Manager Parameter Store
    # DOCKER_USERNAME: /codebuild/docker/username
    # DOCKER_PASSWORD: /codebuild/docker/password
  # secrets-manager:
    # Use AWS Secrets Manager for sensitive data
    # DB_PASSWORD: prod/db/password:password

# Build phases
phases:
  # Pre-build phase - login to ECR and prepare environment
  pre_build:
    commands:
      - echo "Starting pre-build phase at `date`"
      - echo "Logging in to Amazon ECR..."
      
      # Get AWS account ID and region
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      
      # Login to Amazon ECR
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
      
      # Check if repository exists, create if not
      - |
        if ! aws ecr describe-repositories --repository-names ${IMAGE_REPO_NAME} --region ${AWS_DEFAULT_REGION} 2>/dev/null; then
          echo "Creating ECR repository ${IMAGE_REPO_NAME}..."
          aws ecr create-repository \
            --repository-name ${IMAGE_REPO_NAME} \
            --image-scanning-configuration scanOnPush=true \
            --encryption-configuration encryptionType=AES256 \
            --region ${AWS_DEFAULT_REGION}
        fi
      
      # Set image tag with commit SHA and timestamp
      - export IMAGE_TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}"
      - export BUILD_TIMESTAMP=$(date +%Y%m%d-%H%M%S)
      - export IMAGE_URI=${ECR_REGISTRY}/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - export IMAGE_URI_LATEST=${ECR_REGISTRY}/${IMAGE_REPO_NAME}:latest
      
      - echo "Building Docker image with tag ${IMAGE_TAG}"
      - echo "ECR URI will be ${IMAGE_URI}"

  # Build phase - build Docker image
  build:
    commands:
      - echo "Starting build phase at `date`"
      - echo "Building Docker image..."
      
      # Build the Docker image
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker build -t ${IMAGE_REPO_NAME}:latest .
      
      # Tag image for ECR
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${IMAGE_URI}
      - docker tag ${IMAGE_REPO_NAME}:latest ${IMAGE_URI_LATEST}
      
      - echo "Docker image built successfully"

  # Post-build phase - push to ECR and create artifacts
  post_build:
    commands:
      - echo "Starting post-build phase at `date`"
      
      # Push both tagged and latest images to ECR
      - echo "Pushing Docker image to ECR..."
      - docker push ${IMAGE_URI}
      - docker push ${IMAGE_URI_LATEST}
      
      # Get image digest for verification
      - export IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${IMAGE_URI})
      - echo "Image pushed with digest ${IMAGE_DIGEST}"
      
      # Optional: Scan image for vulnerabilities
      - echo "Waiting for image scan results..."
      - |
        aws ecr wait image-scan-complete \
          --repository-name ${IMAGE_REPO_NAME} \
          --image-id imageTag=${IMAGE_TAG} \
          --region ${AWS_DEFAULT_REGION} || true
      
      # Get scan findings
      - |
        SCAN_FINDINGS=$(aws ecr describe-image-scan-findings \
          --repository-name ${IMAGE_REPO_NAME} \
          --image-id imageTag=${IMAGE_TAG} \
          --region ${AWS_DEFAULT_REGION} 2>/dev/null || echo "Scan not available")
        echo "Scan findings: ${SCAN_FINDINGS}"
      
      # Create deployment configuration file
      - echo "Creating deployment artifact..."
      - |
        cat > deployment-config.json <<EOF
        {
          "imageUri": "${IMAGE_URI}",
          "imageTag": "${IMAGE_TAG}",
          "repository": "${IMAGE_REPO_NAME}",
          "region": "${AWS_DEFAULT_REGION}",
          "buildTime": "${BUILD_TIMESTAMP}",
          "commitId": "${CODEBUILD_RESOLVED_SOURCE_VERSION}"
        }
        EOF
      
      - echo "Build completed successfully at `date`"

# Artifacts to be uploaded to S3 (optional)
artifacts:
  files:
    - deployment-config.json
    - docker-compose.yml
    - nginx.conf
  name: governance-tool-artifacts-${CODEBUILD_BUILD_NUMBER}

# Cache Docker layers to speed up builds (optional)
cache:
  paths:
    - '/root/.docker/**/*'

# Build reports (optional - for test results)
# reports:
#   test-results:
#     files:
#       - 'test-results/**/*'
#     file-format: 'JUNITXML'