version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    IMAGE_REPO_NAME: "data-governance-tool"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - echo "Logging in to Amazon ECR..."
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
      - |
        if ! aws ecr describe-repositories --repository-names ${IMAGE_REPO_NAME} --region ${AWS_DEFAULT_REGION} 2>/dev/null; then
          echo "Creating ECR repository ${IMAGE_REPO_NAME}..."
          aws ecr create-repository --repository-name ${IMAGE_REPO_NAME} --image-scanning-configuration scanOnPush=true --encryption-configuration encryptionType=AES256 --region ${AWS_DEFAULT_REGION}
        fi
      - export IMAGE_TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}"
      - export BUILD_TIMESTAMP=$(date +%Y%m%d-%H%M%S)
      - export IMAGE_URI=${ECR_REGISTRY}/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - export IMAGE_URI_LATEST=${ECR_REGISTRY}/${IMAGE_REPO_NAME}:latest
      - echo "Building Docker image with tag ${IMAGE_TAG}"
      - echo "ECR URI will be ${IMAGE_URI}"

  build:
    commands:
      - echo "Starting build phase"
      - echo "Building Docker image..."
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker build -t ${IMAGE_REPO_NAME}:latest .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${IMAGE_URI}
      - docker tag ${IMAGE_REPO_NAME}:latest ${IMAGE_URI_LATEST}
      - echo "Docker image built successfully"

  post_build:
    commands:
      - echo "Starting post-build phase"
      - echo "Pushing Docker image to ECR..."
      - docker push ${IMAGE_URI}
      - docker push ${IMAGE_URI_LATEST}
      - export IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${IMAGE_URI})
      - echo "Image pushed with digest ${IMAGE_DIGEST}"
      - echo "Waiting for image scan results..."
      - aws ecr wait image-scan-complete --repository-name ${IMAGE_REPO_NAME} --image-id imageTag=${IMAGE_TAG} --region ${AWS_DEFAULT_REGION} || true
      - SCAN_FINDINGS=$(aws ecr describe-image-scan-findings --repository-name ${IMAGE_REPO_NAME} --image-id imageTag=${IMAGE_TAG} --region ${AWS_DEFAULT_REGION} 2>/dev/null || echo "Scan not available")
      - echo "Scan findings ${SCAN_FINDINGS}"
      - echo "Creating deployment artifact..."
      - printf '{"imageUri":"%s","imageTag":"%s","repository":"%s","region":"%s","buildTime":"%s","commitId":"%s"}' "${IMAGE_URI}" "${IMAGE_TAG}" "${IMAGE_REPO_NAME}" "${AWS_DEFAULT_REGION}" "${BUILD_TIMESTAMP}" "${CODEBUILD_RESOLVED_SOURCE_VERSION}" > deployment-config.json
      - echo "Build completed successfully"

artifacts:
  files:
    - deployment-config.json
    - docker-compose.yml
    - nginx.conf
  name: governance-tool-artifacts

cache:
  paths:
    - '/root/.docker/**/*'
